{% set name = "pytest-mock" %}
{% set version = "1.2" %}
{% set hash_type = "md5" %}
{% set hash = "a7fa820f7bc71698660945836ff93c73" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/p/pytest-mock/pytest-mock-{{ version }}.zip
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pytest
    - setuptools
  run:
    - python
    - pytest
    - mock  # [py26 or py27]

test:
  imports:
    - pytest_mock

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  summary: Thin-wrapper around the mock package for easier use with py.test

extra:
  recipe-maintainers:
    - nicoddemus