{% set version = "3.8.2" %}

package:
  name: pytest-mock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-mock/pytest-mock-{{ version }}.tar.gz
  sha256: 77f03f4554392558700295e05aed0b1096a20d4a60a4f3ddcde58b0c31c8fca2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - pytest >=5.0
    - python >=3.7

test:
  requires:
    - pip
    - pytest-asyncio
    - pytest >=7.0
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    - pytest --help

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test

extra:
  recipe-maintainers:
    - nicoddemus
