{% set version = "3.7.0" %}

package:
  name: pytest-mock
  version: 1

source:
  url: https://pypi.io/packages/source/p/pytest-mock/pytest-mock-{{ version }}.tar.gz
  sha256: 5112bd92cc9f186ee96e1a92efc84969ea494939c3aead39c50f421c4cc69534

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - pytest >=5.0

test:
  requires:
    - pytest-asyncio
    - setuptools
    - pip
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    - pytest --help
    - pytest tests

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test

extra:
  recipe-maintainers:
    - nicoddemus
