{% set name = "pytest-mock" %}
{% set version = "3.5.0" %}
{% set hash = "4992db789175540d40a193bc60e987b1e69f1a989adad525a44e581c82149b14" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
  run:
    - python >=3.5
    - pytest

test:
  requires:
    - setuptools
    - pytest-asyncio
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pytest --help
    - pytest tests

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test

extra:
  recipe-maintainers:
    - nicoddemus
