{% set version = "3.14.1" %}

package:
  name: pytest-mock
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-mock/pytest_mock-{{ version }}.tar.gz
  sha256: 159e9edac4c451ce77a5cdb9fc5d1100708d2dd4ba3c3df572f14097351af80e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - pytest >=5.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest-asyncio
    - pytest >=7.0
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - pytest_mock
  commands:
    - pip check
    - pytest --help

about:
  home: https://github.com/pytest-dev/pytest-mock
  license: MIT
  license_file: LICENSE
  summary: Thin-wrapper around the mock package for easier use with py.test

extra:
  recipe-maintainers:
    - nicoddemus
